// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("InfluxDB.WriteOnly")]
[assembly: AssemblyProductAttribute("InfluxDB.WriteOnly")]
[assembly: AssemblyDescriptionAttribute("Write-only client for InfluxDB")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "InfluxDB.WriteOnly";
        internal const System.String AssemblyProduct = "InfluxDB.WriteOnly";
        internal const System.String AssemblyDescription = "Write-only client for InfluxDB";
        internal const System.String AssemblyFileVersion = "2.0.0";
        internal const System.String AssemblyVersion = "2.0.0";
        internal const System.String AssemblyInformationalVersion = "2.0.0";
    }
}
